OBJECT_NOT_FOUND_EXCEPTION_MESSAGE = "Object with ID {0} not found."
PAGE_NOT_FOUND_EXCEPTION_MESSAGE = "Page {0} not found. The max number os pages is {1}."
REQUIRED_FIELD_EXCEPTION_MESSAGE = "The field '{0}' is required."
NOT_SUPPORTED_TYPES_EXCEPTION_MESSAGE = "The type '{0}' is not supported."
DUPLICATED_ENUM_CODE = "The code {0} is duplicated."