BASE_URL = f'my-notes/api/v1/annotation/'

NOTE_VIEW_NAME = 'notes'
NOTE_URL = f'{BASE_URL}{NOTE_VIEW_NAME}'

FAKE_NOTE_ID = '62b35377d0f769338f8ae117'
PICTURE_VIEW_NAME = 'pictures'
PICTURE_URL = f'{NOTE_URL}/{FAKE_NOTE_ID}/{PICTURE_VIEW_NAME}'

FAKE_PICTURE_ID = '62b1f25dd80d6f783ae080f9'
COMMENT_VIEW_NAME = 'comments'
COMMENT_URL = f'{BASE_URL}{PICTURE_VIEW_NAME}/{FAKE_PICTURE_ID}/{COMMENT_VIEW_NAME}'



LINK_VIEW_NAME = 'links'
LINK_URL = f'{NOTE_URL}/{FAKE_NOTE_ID}/{LINK_VIEW_NAME}'

TAG_VIEW_NAME = 'tags'
TAG_URL = f'{BASE_URL}{TAG_VIEW_NAME}'

MOOD_VIEW_NAME = 'moods'
MOOD_URL = f'{BASE_URL}{MOOD_VIEW_NAME}'
